//> using scala "3.5.1-RC1-bin-20240530-01b404f-NIGHTLY"
//> using option "-source:future"
//> using option "-language:experimental.modularity"
//> using option "-language:experimental.namedTuples"
//> using option "-language:experimental.erasedDefinitions"
//> using option "-Xkind-projector:underscores"
//> using option "-deprecation"
