//> using scala 3.5.1
//> using option -source:future
//> using option -language:experimental.modularity
//> using option -language:experimental.namedTuples
//> using option -Xkind-projector:underscores
//> using option -deprecation
//> using option -Wunused:all
//> using dep io.github.arainko::ducktape:0.2.2
//> using dep "org.scalameta::munit:1.0.2"
